#!/bin/bash
docker service rm vnfm
docker service rm VDU1
docker service rm VDU2
docker service rm VDU3
docker service rm VDU4
docker network rm admin_net
docker network rm VL1_2
docker network rm VL1_3
docker network rm VL1_4
docker network rm VL2_3
docker network rm VL2_4
docker network rm VL3_4
